import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import StoryblokProvider from '@/components/StoryblokProvider';
import BootstrapClient from '@/components/BootstrapClient';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	const currentYear = new Date().getFullYear();
	return (
		<StoryblokProvider>
			<html lang="en">
				<body>
					<BootstrapClient />
					{children}
					<footer>All rights reserved © {currentYear} </footer>
				</body>
			</html>
		</StoryblokProvider>
	);
}
